artifact_uri: file:///d:/datascience/campusx/PROJECTS/Swiggy_project_Experimentation/TRACKING_URI_HERE/555554255995184736/62b9cdf4d6da4222bb952a539389d8bb/artifacts
end_time: 1763633615535
entry_point_name: ''
experiment_id: '555554255995184736'
lifecycle_stage: active
run_id: 62b9cdf4d6da4222bb952a539389d8bb
run_name: weights_L0.85_C0.15
source_name: ''
source_type: 4
source_version: ''
start_time: 1763633615419
status: 3
tags: []
user_id: apoor
