artifact_uri: file:///d:/datascience/campusx/PROJECTS/Swiggy_project_Experimentation/TRACKING_URI_HERE/555554255995184736/dc5a097ad384414ca0f1e29982063f3b/artifacts
end_time: 1763633613982
entry_point_name: ''
experiment_id: '555554255995184736'
lifecycle_stage: active
run_id: dc5a097ad384414ca0f1e29982063f3b
run_name: weights_L0.30_C0.70
source_name: ''
source_type: 4
source_version: ''
start_time: 1763633613855
status: 3
tags: []
user_id: apoor
