artifact_uri: file:///d:/datascience/campusx/PROJECTS/Swiggy_project_Experimentation/TRACKING_URI_HERE/555554255995184736/9f8c764fcbe54874bfb0d8edaeb77ebf/artifacts
end_time: 1763633614386
entry_point_name: ''
experiment_id: '555554255995184736'
lifecycle_stage: active
run_id: 9f8c764fcbe54874bfb0d8edaeb77ebf
run_name: weights_L0.45_C0.55
source_name: ''
source_type: 4
source_version: ''
start_time: 1763633614264
status: 3
tags: []
user_id: apoor
