artifact_uri: file:///d:/datascience/campusx/PROJECTS/Swiggy_project_Experimentation/TRACKING_URI_HERE/555554255995184736/ec1f1b16f43f4a6a93c19173df1cc4dd/artifacts
end_time: 1763633613544
entry_point_name: ''
experiment_id: '555554255995184736'
lifecycle_stage: active
run_id: ec1f1b16f43f4a6a93c19173df1cc4dd
run_name: weights_L0.15_C0.85
source_name: ''
source_type: 4
source_version: ''
start_time: 1763633613420
status: 3
tags: []
user_id: apoor
