artifact_uri: file:///d:/datascience/campusx/PROJECTS/Swiggy_project_Experimentation/TRACKING_URI_HERE/555554255995184736/3c7aaae212f04d76b58cab9dbfb9806e/artifacts
end_time: 1763633613700
entry_point_name: ''
experiment_id: '555554255995184736'
lifecycle_stage: active
run_id: 3c7aaae212f04d76b58cab9dbfb9806e
run_name: weights_L0.20_C0.80
source_name: ''
source_type: 4
source_version: ''
start_time: 1763633613559
status: 3
tags: []
user_id: apoor
