artifact_uri: file:///d:/datascience/campusx/PROJECTS/Swiggy_project_Experimentation/TRACKING_URI_HERE/555554255995184736/335aa7d5ba87499eb1610d97ae50527a/artifacts
end_time: 1763633613264
entry_point_name: ''
experiment_id: '555554255995184736'
lifecycle_stage: active
run_id: 335aa7d5ba87499eb1610d97ae50527a
run_name: weights_L0.05_C0.95
source_name: ''
source_type: 4
source_version: ''
start_time: 1763633613136
status: 3
tags: []
user_id: apoor
