artifact_location: file:///d:/datascience/campusx/PROJECTS/Swiggy_project_Experimentation/TRACKING_URI_HERE/0
creation_time: 1763633554750
experiment_id: '0'
last_update_time: 1763633554750
lifecycle_stage: active
name: Default
