artifact_uri: file:///d:/datascience/campusx/PROJECTS/Swiggy_project_Experimentation/TRACKING_URI_HERE/555554255995184736/f1f544df9f5f43f1a8f3e033b9f9def0/artifacts
end_time: 1763633613120
entry_point_name: ''
experiment_id: '555554255995184736'
lifecycle_stage: active
run_id: f1f544df9f5f43f1a8f3e033b9f9def0
run_name: weights_L0.00_C1.00
source_name: ''
source_type: 4
source_version: ''
start_time: 1763633612879
status: 3
tags: []
user_id: apoor
