artifact_uri: file:///d:/datascience/campusx/PROJECTS/Swiggy_project_Experimentation/TRACKING_URI_HERE/555554255995184736/5ab883bcda56499b8127e4593fc8c5c1/artifacts
end_time: 1763633614546
entry_point_name: ''
experiment_id: '555554255995184736'
lifecycle_stage: active
run_id: 5ab883bcda56499b8127e4593fc8c5c1
run_name: weights_L0.50_C0.50
source_name: ''
source_type: 4
source_version: ''
start_time: 1763633614405
status: 3
tags: []
user_id: apoor
