artifact_uri: file:///d:/datascience/campusx/PROJECTS/Swiggy_project_Experimentation/TRACKING_URI_HERE/555554255995184736/314c877d15a2462c8cbc2e3158ab1c20/artifacts
end_time: 1763633614859
entry_point_name: ''
experiment_id: '555554255995184736'
lifecycle_stage: active
run_id: 314c877d15a2462c8cbc2e3158ab1c20
run_name: weights_L0.60_C0.40
source_name: ''
source_type: 4
source_version: ''
start_time: 1763633614723
status: 3
tags: []
user_id: apoor
