artifact_uri: file:///d:/datascience/campusx/PROJECTS/Swiggy_project_Experimentation/TRACKING_URI_HERE/555554255995184736/f21f020210a8427580b4aa95dcab69a2/artifacts
end_time: 1763633614705
entry_point_name: ''
experiment_id: '555554255995184736'
lifecycle_stage: active
run_id: f21f020210a8427580b4aa95dcab69a2
run_name: weights_L0.55_C0.45
source_name: ''
source_type: 4
source_version: ''
start_time: 1763633614565
status: 3
tags: []
user_id: apoor
