artifact_uri: file:///d:/datascience/campusx/PROJECTS/Swiggy_project_Experimentation/TRACKING_URI_HERE/555554255995184736/393af1af9c334672b62bf28061da7d9d/artifacts
end_time: 1763633615668
entry_point_name: ''
experiment_id: '555554255995184736'
lifecycle_stage: active
run_id: 393af1af9c334672b62bf28061da7d9d
run_name: weights_L0.90_C0.10
source_name: ''
source_type: 4
source_version: ''
start_time: 1763633615551
status: 3
tags: []
user_id: apoor
