artifact_uri: file:///d:/datascience/campusx/PROJECTS/Swiggy_project_Experimentation/TRACKING_URI_HERE/555554255995184736/3fb0cf92fd944ac5be99f969edaf8dce/artifacts
end_time: 1763633614993
entry_point_name: ''
experiment_id: '555554255995184736'
lifecycle_stage: active
run_id: 3fb0cf92fd944ac5be99f969edaf8dce
run_name: weights_L0.65_C0.35
source_name: ''
source_type: 4
source_version: ''
start_time: 1763633614874
status: 3
tags: []
user_id: apoor
