artifact_uri: file:///d:/datascience/campusx/PROJECTS/Swiggy_project_Experimentation/TRACKING_URI_HERE/555554255995184736/24e4f40eb30f479c961ac326f1881a8b/artifacts
end_time: 1763633615128
entry_point_name: ''
experiment_id: '555554255995184736'
lifecycle_stage: active
run_id: 24e4f40eb30f479c961ac326f1881a8b
run_name: weights_L0.70_C0.30
source_name: ''
source_type: 4
source_version: ''
start_time: 1763633615008
status: 3
tags: []
user_id: apoor
