artifact_location: file:///d:/datascience/campusx/PROJECTS/Swiggy_project_Experimentation/TRACKING_URI_HERE/555554255995184736
creation_time: 1763633555282
experiment_id: '555554255995184736'
last_update_time: 1763633555282
lifecycle_stage: active
name: Exp 5 - Weighted Modeling
