artifact_uri: file:///d:/datascience/campusx/PROJECTS/Swiggy_project_Experimentation/TRACKING_URI_HERE/555554255995184736/dc299fda073046b6ae1fd99a2568eb88/artifacts
end_time: 1763633615267
entry_point_name: ''
experiment_id: '555554255995184736'
lifecycle_stage: active
run_id: dc299fda073046b6ae1fd99a2568eb88
run_name: weights_L0.75_C0.25
source_name: ''
source_type: 4
source_version: ''
start_time: 1763633615143
status: 3
tags: []
user_id: apoor
